# Generated by Django 5.2.12 on 2026-05-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0020_alter_adminstration_id_alter_appointment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_record',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='medical_record',
            name='disc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medical_record',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='medical_records/'),
        ),
    ]
