# Generated by Django 5.2.12 on 2026-05-30 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0021_alter_medical_record_date_alter_medical_record_disc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical_record',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health.patient'),
        ),
        migrations.AlterField(
            model_name='medical_record',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medical_record',
            name='disc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
